name: cocktail_master
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.0.0
  dio: ^5.5.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  shared_preferences: ^2.2.3
  envied: ^0.5.4
  
 
  flex_color_scheme: ^8.0.0 
  
  google_fonts: ^6.2.1
  intl: ^0.19.0
  gap: ^3.0.0
  flutter_form_builder: ^9.2.1
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.6
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1
  envied_generator: ^0.5.4

flutter:
  uses-material-design: true